config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'

  resources :carts, only: [:show]
  get '/cart_blank', to: 'carts#cart_blank'
  
  resources :items do
    post '/add_item', to: 'carts#add_item'
    put '/update_item', to: 'carts#update_item'
    delete '/delete_item', to: 'carts#delete_item'
  end

  resources :orders, only: [:index, :new, :create, :destroy]
  get '/done', to: 'orders#done'

  resources :cards, only: [:new, :create]

  get '/search', to: 'searches#index'
  get '/sort_order', to: 'searches#sort_order'
  # get 'search/keyword'
  # get 'search/sort_order'
end

app/models/address.rb
class Address < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  belongs_to_active_hash :prefecture
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :items, through: :cart_items
  belongs_to :user
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
  has_many :order_details
end

app/models/format.rb
class Format < ActiveHash::Base
  self.data = [
    { id: 1, name: 'LP(レコード)' },
    { id: 2, name: '7"(レコード)' },
    { id: 3, name: '10"(レコード)' },
    { id: 4, name: '12"(レコード)' },
    { id: 5, name: 'CD' },
    { id: 6, name: 'DVD' },
    { id: 7, name: 'BLU-RAY(ブルーレイ)' },
    { id: 8, name: 'BOOK' },
    { id: 9, name: 'GOODS' },
    { id: 10, name: 'CASSETTE TAPE' },
    { id: 11, name: 'その他' }
  ]
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: 'ROCK/POPS/INDIE' },
    { id: 2, name: 'OLD ROCK' },
    { id: 3, name: 'NOISE/AVANT-GARDE' },
    { id: 4, name: 'HARD ROCK/HEAVY METAL' },
    { id: 5, name: 'PUNK' },
    { id: 6, name: 'PROGRESSIVE ROCK' },
    { id: 7, name: 'JAZZ' },
    { id: 8, name: 'SOUL/BLUES' },
    { id: 9, name: 'LATIN/BRAZIL/WORLD MUSIC' },
    { id: 10, name: 'REGGAE' },
    { id: 11, name: 'CLUB/DANCE' },
    { id: 12, name: 'HIP HOP/日本語RAP' },
    { id: 13, name: 'CLASSIC' },
    { id: 14, name: 'JAPANESE ROCK・POPS/INDIES' },
    { id: 15, name: '昭和歌謡' },
    { id: 16, name: '映画DVD・ブルーレイ／サントラ' },
    { id: 17, name: 'CD・レコードアクセサリー' },
    { id: 18, name: 'グッズ' }
  ]
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_one_attached :image
  belongs_to_active_hash :genre
  belongs_to_active_hash :format
  belongs_to_active_hash :status

  validates :title, :artist, :text, :genre_id, :format_id, :status_id,
            :price, :stock, :image, presence: true

  validates :price, numericality: { only_integer: true, message: 'は半角数字で入力してください' }
end

app/models/item_order.rb
class ItemOrder
  include ActiveModel::Model

  attr_accessor :last_name, :first_name, :last_name_kana, :first_name_kana, 
                :postal_code, :prefecture_id, :city, :block, :building, :phone_number,
                :card_token, :customer_token,
                :total_price, :user_id, :address_id, :is_cancel, :order_id, :cart_item_id

  with_options presence: true do
    validates :last_name, :first_name,
                format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "は全角で入力してください"}
    validates :last_name_kana,:first_name_kana,
                format: { with: /\A[ァ-ヶー－]+\z/, message: "は全角カタカナで入力してください"}
    validates :postal_code,
                format: { with: /\A\d{3}[-]\d{4}\z/, message: 'にはハイフンが必要です' }
    validates :prefecture_id, numericality: { other_than: 0 }
    validates :city
    validates :block
    validates :phone_number, format: { with: /\A\d{10,11}\z/, message: 'が正しくありません' }
    validates :card_token
  end

  def save
    @address = Address.create(last_name: last_name, first_name: first_name, last_name_kana: last_name_kana, first_name_kana: first_name_kana,
                   postal_code: postal_code, prefecture_id: prefecture_id, city: city, block: block, building: building, phone_number: phone_number, user_id: user_id)
    @order = Order.create(total_price: total_price, user_id: user_id, address_id: @address.id)
    #以下,order_detailsテーブルに値を保存する処理
    @cart = Cart.order(created_at: :DESC).find_by(user_id: user_id)
    @cart_items = CartItem.where(cart_id: @cart.id)
    #gem 'activerecord-import'を使用し、複数のcart_itemをorder_detailsテーブルに保存する
    order_details = []
    @cart_items.each do |cart_item|
      order_details << OrderDetail.new(order_id: @order.id, cart_item_id: cart_item.id)
    end
    OrderDetail.import order_details
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :cart_item
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

  self.data = [
               {id: 0, name: '--'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, 
               {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, 
               {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, 
               {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, 
               {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, 
               {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, 
               {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, 
               {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, 
               {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, 
               {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, 
               {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, 
               {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, 
               {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, 
               {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, 
               {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, 
               {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
              ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: 'S 未開封' },
    { id: 2, name: 'A 無傷' },
    { id: 3, name: 'A ほぼ無傷' },
    { id: 4, name: 'B ほぼ美品状態' },
    { id: 5, name: 'B ノイズほとんどなし' },
    { id: 6, name: 'B 多少の汚れあり' },
    { id: 7, name: 'B ノイズはあるが十分聴ける' },
    { id: 8, name: 'B ノイズがある' },
    { id: 9, name: 'C かなりノイズがある' }
  ]
end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart, dependent: :destroy
  has_one :card, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :email, format: { with: /\A\S+@\S+\.\S+\z/, message: 'は@を含む必要があります' }
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])\w{6,}\z/.freeze
  validates :password,
            format: { with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください' }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def stock_array_maker(cart_item)              #在庫(stock)の数をプルダウン表示する
    current_stock_array = []                    #配列を生成

    stock = cart_item.item.stock
    stock.times do |quantity|                   #stockの現在の在庫数まで、ループを回す。
      if quantity < stock                       #quantityが在庫未満かどうか？
        current_stock_array << quantity + 1     #quantityは0からスタートしているので、1足した数を入れる必要がある。
      else
        break                                   #ループを抜ける
      end
    end
    current_stock_array # 戻り値
  end

  def cart_item_price_calc(cart_item)
    cart_item.item.price * cart_item.quantity   #商品価格×数量 = 各商品ごとの合計金額
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RcoShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application' %>
    <script src="https://js.pay.jp/" , type="text/javascript"></script>
    <script type="text/javascript" src="https://postcode-jp.com/js/postcodejp.js" charset="utf-8"></script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-wrapper">
    <%= image_tag '/images/RCO_BECO.svg', class:"footer-logo" %>
    <div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class="header-top-nav">
    <% if user_signed_in? && current_user.admin? %>
      <%= link_to '>>商品出品', new_item_path, class:"new-item-link" %>
    <% end %>
  </div>
  <div class="header-container">
    <div class="header-left">
      <%= link_to image_tag('/images/rco_logo.svg', class:"rco-logo"), root_path %>
    </div>
    <div class="header-right">
      <%= search_form_for @q, url: search_path, class:"search-form", method: :get do |f| %>
        <%= f.text_field :title_or_artist_cont, class:"input-box", placeholder:"アルバムタイトル、アーティスト名などで検索" %>
        <%= f.submit value:"", class:"search-button" %>
      <% end %>
      <div class="cart">
        <% if user_signed_in? && Cart.exists?(session[:cart_id]) %>
          <%= link_to "/carts/#{session[:cart_id]}" do %>
            <%= image_tag "/images/icon_crt.svg", class:"cart-icon" %>
          <% end %>
        <% elsif user_signed_in? && !Cart.nil? %>
          <%= link_to cart_blank_path do %>
            <%= image_tag "/images/icon_crt.svg", class:"cart-icon" %>
          <% end %>
        <% else %>
          <%= link_to new_user_session_path do %>
            <%= image_tag "/images/icon_crt.svg", class:"cart-icon" %>
          <% end %>
        <% end %>
      </div>
      <div class="login-logout">
        <% if user_signed_in? %>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
        <% else %>
          <%= link_to image_tag("/images/btn_login.png", class:"login"), new_user_session_path %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="menu-nav">
    <div class="menu-left">
    </div>
    <div class="menu-right">
      <% if user_signed_in? %>
        こんにちは、<%= current_user.nickname %>さん
      <% end %>
    </div>
  </div>
</header>

app/views/shared/_search.html.erb
<%= render "shared/header" %>
<div class="search-wrapper">
  <div class="search-main-field">
    <%# 詳細検索サイドバー %>
    <div class="search-side">
      <%= search_form_for @q, url: sort_order_path, method: :get, local: true do |f| %>
        <%= f.select( :sorts, { '並び替え': 'id desc', '価格の安い順': 'price asc', '価格の高い順': 'price desc', '出品の古い順': 'updated_at asc', '出品の新しい順': 'updated_at desc' } ,
           { selected: params[:q][:sorts] }, { onchange: 'this.form.submit()'} ) %>
        <br>
        <h2 class="search-side-head">詳細検索</h2>

        <%= f.label :title_or_artist, "キーワードを追加する" %>
        <%= f.text_field :title_or_artist_cont %>

        <%= f.label :genre_id, "ジャンルを選択する" %>
        <%= f.collection_select :genre_id_eq, Genre.all, :id, :name, include_blank:"選択してください" %>

        <%= f.label :format_id, "フォーマットを選択する" %>
        <%= f.collection_select :format_id_eq, Format.all, :id, :name, include_blank:"選択してください" %>

        <%= f.label :price_eq, "価格" %><br>
        <%= f.text_field :price_gteq, placeholder:"¥MIN", class:"search-price" %><span>〜</span>
        <%= f.text_field :price_lteq, placeholder:"¥MAX", class:"search-price" %>

        <%= f.submit class:"search-side-submit" %>
      <% end %>
    </div>

    <%# 検索結果メッセージ %>
    <div class="search-result">
      <h2 class="search-result-message">
        <span>「</span><%= "#{params[:q][:title_or_artist_cont]}" %><span>」の検索結果</span>
        <%= "#{@results.length}" %><span>件</span>
      </h2>
      <%# 検索結果一覧 %>
      <div class="result-wrapper">
        <% @results.each do |result| %>
          <div class="item">
            <%= link_to item_path(result), class:"item-path" do %>
              <div class="item-image-content">
                <%= image_tag result.image, class:"item-image" %>
              </div>
            <% end %>
            <div class="item-format">
              <%= result.format.name %>
            </div>
            <div class="item-artist">
              <%= result.artist %>
            </div>
            <%= link_to item_path(result), class:"item-path" do %>
              <div class="item-title">
                <%= result.title %>
              </div>
              <div class="item-price">
                <%= result.price %>円(税込み)
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag('/images/rco_logo.svg', class:"rco-logo"), root_path %>
</header>