config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'

  resources :carts, only: [:show]
  get '/cart_blank', to: 'carts#cart_blank'
  
  resources :items do
    post '/add_item', to: 'carts#add_item'
    put '/update_item', to: 'carts#update_item'
    delete '/delete_item', to: 'carts#delete_item'
  end

  resources :orders, only: [:index, :new, :create, :destroy]
  get '/done', to: 'orders#done'

  resources :cards, only: [:new, :create]

  get '/search', to: 'searches#index'
  get '/sort_order', to: 'searches#sort_order'
  # get 'search/keyword'
  # get 'search/sort_order'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  require 'payjp'
  def index
    #注文一覧       マイページで表示
    #deviseのcurrent_userを渡す
    #@order = Order.find_by(user_id: current_user.id)
    #@order_detailの一覧も表示 
  end

  def new
    @cart_items = current_cart.cart_items.order(created_at: :DESC)
    @item_order = ItemOrder.new
    #住所入力、保存（住所がある場合は、住所を表示する）
      #addressが存在する     address#show
      #addressが存在しない   address#new
    #クレジット情報入力、保存（カード情報がある場合は、カード情報を表示する）
      #cardが存在する場合     card#show
      #cardが存在しない場合    card#new
  end

  def create
    #ordersテーブル,order_derailsテーブル,addressesテーブルに値が保存される。
    @item_order = ItemOrder.new(item_order_params)
    @cart_items = CartItem.where(cart_id: current_cart.id)

    if @item_order.valid?
      payment
      @item_order.save
      session.delete(:cart_id)

      @cart_items.each do |cart_item|
        item = Item.find(cart_item.item_id)
        item.update(stock: item.stock - cart_item.quantity)
      end
      redirect_to done_path
    else
      render :new
    end
  end

  def destroy
    @order = Order.find(id: params[:id])
    @order.is_cancel = 1
    #注文のキャンセル(is_cancelを1にする)
    #マイページで実装
  end
  
  def done
  end

  private
  def item_order_params
    params.require(:item_order).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :prefecture_id,
                  :city, :block, :building, :phone_number, :card_token).merge(user_id: current_user.id, total_price: params[:total_price])
  end

  def payment
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    Payjp::Charge.create(
      amount: params[:total_price],
      card: params[:item_order][:card_token],
      currency: 'jpy'
    )
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/done.html.erb
<%= render "shared/second-header"%>
<div class="done-wrapper">
  <h1 class="done-message">
    ご注文ありがとうございます！
  </h1>
  <p class="done-sub-message">
    注文を承りました。発送手続きに入ります。
  </p>
  <%= link_to "トップページへもどる", root_path, class:"done-top-link" %>
</div>

app/views/orders/new.html.erb
<%= render "shared/second-header"%>
<div class="order-wrapper">
  <div class="order-container"> 
    <div class="order-head-messages">
      <h1>注文内容の確認</h1>
      <p>カートには以下の商品が入っています。ご確認ください。</p>
    </div>
    <%# 注文商品を一覧表示 %>
    <div class="items-table">
      <table border="1" bordercolor="white" width="700px;">
        <thead>
          <tr>
            <th class="order-table-head" style="width:35%;" colspan="2">商品名</th>
            <th class="order-table-head" style="width:10%;">販売価格</th>
            <th class="order-table-head" style="width:6%;">数量</th>
            <th class="order-table-head" style="width:12%;">小計</th>
          </tr>
        </thead>
        <tbody>
          <% @cart_items.each do |cart_item| %>
            <tr>
              <td class="order-image">
                <%= image_tag cart_item.item.image, class:"order-item-image" %>
              </td>
              <td class="order-item">
                <%= cart_item.item.title%>/
                <%= cart_item.item.artist %>
              </td>
              <td class="order-price">
                <%= cart_item.item.price %>円
              </td>
              <td class="order-quantity">
                <%= cart_item.quantity %>
              </td>
              <td class="order-item-total-price">
                <span class="item-total-price"><%= cart_item_price_calc(cart_item) %></span>円(税込)
              </td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td class="order-total-price" colspan="3">合計</td>
            <td id="cart-total-price"></td>
            <td class="yen">円(税込)</td>
          </tr>
        </tfoot>
      </table>
      <%= link_to "編集/削除", cart_path(@cart), class:"to-cart-link" %>
    </div>

    <%# 送付先、カード情報入力フォーム %>
    <div class="order-form">
      <%= form_with model: @item_order, url: orders_path, id: "charge-form", local: true do |f| %>
        <div class='credit-card-form'>
        <%= render 'shared/error_messages', model: @item_order %>
        <h1 class="order-form-message">カード情報を入力する</h1>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">カード情報</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_field :number, class:"card-input", id:"card-number", placeholder:"カード番号(半角数字)", maxlength:"16" %>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">有効期限</label>
              <span class="indispensable">必須</span>
            </div>
            <div class='input-expiration-date-wrap'>
              <%= f.text_field :exp_month, class:"input-expiration-date", id:"card-exp-month", placeholder:"例)3" %>
              <p>月</p>
              <%= f.text_field :exp_year, class:"input-expiration-date", id:"card-exp-year", placeholder:"例)23" %>
              <p>年</p>
            </div>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">セキュリティコード</label>
              <span class="indispensable">必須</span>
            </div> 
            <%= f.text_field :cvc, class:"cvc-input", id:"card-cvc", placeholder:"CVC", maxlength:"4" %>
          </div>
        </div> 

        <h1 class="order-form-message">住所を入力する</h1>

        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">名字</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :last_name, class:"address-input", id:"last-name" %>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">名前</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :first_name, class:"address-input", id:"first-name" %>
        </div>
        <div class="form-group">
          <div class='form-text-wrap'>
            <label class="form-text">名字(カナ)</label>
            <span class="indispensable">必須</span>
          </div>
          <%= f.text_field :last_name_kana, class:"address-input", id:"last-name-kana" %>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">名前(カナ)</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_field :first_name_kana, class:"address-input", id:"first-name-kana" %>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">郵便番号</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_field :postal_code, class:"address-input", id:"sample1_zip", placeholder:"ハイフンが必要です" %>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">都道府県</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"address-input mdl-js-textfield", id:"stateSelectBox"})%>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">市区町村</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_field :city, class:"address-input", id:"sample1_address2" %>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">それ以降の住所</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_field :block, class:"address-input", id:"sample1_address3" %>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">建物名</label>
            </div>
            <%= f.text_field :building, class:"address-input", id:"building" %>
          </div>
          <div class="form-group">
            <div class='form-text-wrap'>
              <label class="form-text">電話番号</label>
              <span class="indispensable">必須</span>
            </div>
            <%= f.text_field :phone_number, class:"address-input", id:"phone-number" %>
          </div>
          <div class='login-btn'>
            <%= f.submit "注文を確定する" ,class:"order-button" %>
          </div>
      <% end %>
    </div>
  </div>
</div>