config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'

  resources :carts, only: [:show]
  get '/cart_blank', to: 'carts#cart_blank'
  
  resources :items do
    post '/add_item', to: 'carts#add_item'
    put '/update_item', to: 'carts#update_item'
    delete '/delete_item', to: 'carts#delete_item'
  end

  resources :orders, only: [:index, :new, :create, :destroy]
  get '/done', to: 'orders#done'

  resources :cards, only: [:new, :create]

  get '/search', to: 'searches#index'
  get '/sort_order', to: 'searches#sort_order'
  # get 'search/keyword'
  # get 'search/sort_order'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :items, through: :cart_items
  belongs_to :user
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :setup_cart_item!, only: [:show, :add_item, :update_item, :delete_item]
  before_action :authenticate_user!

  def show
    @cart = Cart.find(params[:id])
    @cart_items = current_cart.cart_items.order(created_at: :DESC)
  end

  # 商品一覧画面から、「カートに入れる」を押した時のアクション
  def add_item
    if @cart_item.blank?
      @cart_item = current_cart.cart_items.build(item_id: params[:item_id])
    end
    @cart_item.save
    redirect_to current_cart
  end

  # カート詳細画面から、数量を変更した時のアクション
  def update_item
    @cart_item.update(quantity: params[:quantity].to_i)
    redirect_to current_cart
  end

  # カート詳細画面から、「削除」を押した時のアクション
  def delete_item
    @cart_item.destroy
    redirect_to current_cart
  end
  
  def cart_blank
  end

  private

  def setup_cart_item!
    @cart_item = current_cart.cart_items.find_by(item_id: params[:item_id])
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def stock_array_maker(cart_item)              #在庫(stock)の数をプルダウン表示する
    current_stock_array = []                    #配列を生成

    stock = cart_item.item.stock
    stock.times do |quantity|                   #stockの現在の在庫数まで、ループを回す。
      if quantity < stock                       #quantityが在庫未満かどうか？
        current_stock_array << quantity + 1     #quantityは0からスタートしているので、1足した数を入れる必要がある。
      else
        break                                   #ループを抜ける
      end
    end
    current_stock_array # 戻り値
  end

  def cart_item_price_calc(cart_item)
    cart_item.item.price * cart_item.quantity   #商品価格×数量 = 各商品ごとの合計金額
  end

end

app/views/carts/cart_blank.html.erb
<%= render "shared/header"%>
<div class="cart-wrapper">
  <div class='form-header'>
    <h1 class='form-header-text'>
      ショッピングカート
    </h1>
  </div>
  <p class="cart_blank_message">現在お客様のショッピングカートに商品はありません。</p>
</div>

app/views/carts/show.html.erb
<%= render "shared/header"%>
<div class="cart-wrapper">
  <div class='form-header'>
    <h1 class='form-header-text'>
      ショッピングカート
    </h1>
  </div>
  <div class="cart-container">
    <% @cart_items.each do |cart_item| %>
      <div class="cart-item" data-id=<%= cart_item.id %>>
        <div class="cart-item-left">
          <div class="cart-image">
            <%= image_tag cart_item.item.image, class:"cart-item-image" %>
          </div>
        </div>
        <div class="cart-item-right">
          <div class="cart-item-title">
            <%= cart_item.item.title %>
          </div>
          <div class="cart-item-artist">
            <%= cart_item.item.artist %>
          </div>
          <div class="cart-item-price-change">
            <div class="cart-item-price">
              単価 : <span class="item-price"><%= cart_item.item.price %></span>円(税込)
            </div>
            <div class="cart-item-edit">
              <%= form_with url: "/items/#{cart_item.item_id}/update_item", name: "quantityForm", method: :put do |f| %>
                <%= f.label :quantity, "数量" %>
                <%= f.select :quantity, stock_array_maker(cart_item), name:"quantity", id:"quantity", selected: cart_item.quantity %>
                <%= f.submit "変更", id:"commit", style:"display:none;" %>
              <% end %>
            </div>
          </div>
          <div class="cart-item-price-calc">
            合計 : <span class="item-total-price"><%= cart_item_price_calc(cart_item) %></span>円(税込)
          </div>
          <div class="cart-item-destroy">
            <%= link_to "削除", "/items/#{cart_item.item_id}/delete_item", method: :delete %>
          </div>
        </div>
      </div>
    <% end %>
      <div class="cart-item-total-calc">
        合計 <span id="cart-total-price"></span>円(税込)
      </div>
      <%= link_to new_order_path do %>
        <button class="to-order-btn">レジへ進む</button>
      <% end %>
  </div>
</div>