config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'items#index'

  resources :carts, only: [:show]
  get '/cart_blank', to: 'carts#cart_blank'
  
  resources :items do
    post '/add_item', to: 'carts#add_item'
    put '/update_item', to: 'carts#update_item'
    delete '/delete_item', to: 'carts#delete_item'
  end

  resources :orders, only: [:index, :new, :create, :destroy]
  get '/done', to: 'orders#done'

  resources :cards, only: [:new, :create]

  get '/search', to: 'searches#index'
  get '/sort_order', to: 'searches#sort_order'
  # get 'search/keyword'
  # get 'search/sort_order'
end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :cart_items
  has_many :carts, through: :cart_items
  has_one_attached :image
  belongs_to_active_hash :genre
  belongs_to_active_hash :format
  belongs_to_active_hash :status

  validates :title, :artist, :text, :genre_id, :format_id, :status_id,
            :price, :stock, :image, presence: true

  validates :price, numericality: { only_integer: true, message: 'は半角数字で入力してください' }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :admin_check, only: [:new, :create, :edit, :update, :destroy]
  before_action :item_find, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.order('created_at DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:title, :artist, :text, :genre_id, :country, :format_id, :status_id, :price, :stock, :image)
  end

  def admin_check
    redirect_to root_path unless current_user.admin?
  end

  def item_find
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<%= render "shared/second-header"%>
<%= form_with model: @item, class: 'edit-item-main', local: true do |f| %>
  <div class='form-wrap'>

    <div class='form-header'>
      <h1 class='form-header-text'>
        編集ページ
      </h1>
    </div>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-group">
      <div class="form-text-wrap">
        <label class="form-text">出品画像</label>
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">タイトル</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :title, class:"item-input", id:"title" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">アーティスト</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :artist, class:"item-input", id:"artist" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">商品説明</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :text, class:"item-input-text", id:"title" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">ジャンル</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"hash-select"}) %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">国</label>
      </div>
      <%= f.text_field :country, class:"item-input", id:"country" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">フォーマット</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:format_id, Format.all, :id, :name, {}, {class:"hash-select"}) %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">商品の状態</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"hash-select"}) %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">価格</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :price, class:"int-input", id:"item-price", placeholder:"半角数字" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">在庫数</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :stock, class:"int-input", id:"stock", placeholder:"半角数字" %>
    </div>
    <div class='login-btn'>
      <%= f.submit "編集する" ,class:"login-gray-btn" %>
    </div>
  </div>
<% end %>

<%= form_with model: @item, class: 'edit-item-main', method: :delete, local: true do |f| %>
  <div class="form-wrap">
    <div class='form-header'>
      <h1 class='form-header-text'>
        商品削除
      </h1>
    </div>
    <%# <p class="destroy-notice">一度削除した商品は戻せません</p> %>
    <div class='login-btn'>
      <%= f.submit "削除する" ,class:"login-gray-btn" %>
    </div>
  </div>
<% end %>

app/views/items/index.html.erb
<%= render "shared/header" %>
<div class="main-wrapper">
  <div class="item-wrapper">
    <% @items.each do |item| %>
      <div class="item">
        <%= link_to item_path(item), class:"item-path" do %>
          <div class="item-image-content">
            <%= image_tag item.image, class:"item-image" %>
          </div>
        <% end %>
          <div class="item-format">
            <%= item.format.name %>
          </div>
          <div class="item-artist">
            <%= item.artist %>
          </div>
        <%= link_to item_path(item), class:"item-path" do %>
          <div class="item-title">
            <%= item.title %>
          </div>
          <div class="item-price">
            <%= item.price %>円(税込み)
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<%# <%= render "shared/footer" %>

app/views/items/new.html.erb
<%= render "shared/second-header"%>
<%= form_with model: @item, class: 'new-item-main', local: true do |f| %>
  <div class='form-wrap'>

    <div class='form-header'>
      <h1 class='form-header-text'>
        商品出品
      </h1>
    </div>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-group">
      <div class="form-text-wrap">
        <label class="form-text">出品画像</label>
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">タイトル</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :title, class:"item-input", id:"title" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">アーティスト</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :artist, class:"item-input", id:"artist" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">商品説明</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :text, class:"item-input-text", id:"title" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">ジャンル</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {include_blank:"--"}, {class:"hash-select"}) %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">国</label>
      </div>
      <%= f.text_field :country, class:"item-input", id:"country" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">フォーマット</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:format_id, Format.all, :id, :name, {include_blank:"--"}, {class:"hash-select"}) %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">商品の状態</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:status_id, Status.all, :id, :name, {include_blank:"--"}, {class:"hash-select"}) %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">価格</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :price, class:"int-input", id:"item-price", placeholder:"半角数字" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">在庫数</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_field :stock, class:"int-input", id:"stock", placeholder:"半角数字" %>
    </div>
    <div class='login-btn'>
      <%= f.submit "出品する" ,class:"login-gray-btn" %>
    </div>
  </div>
<% end %>

app/views/items/show.html.erb
<%= render "shared/header" %>
<div class="show-main-wrapper">
  <div class="show-item-wrapper">
    <div class="image-wrapper">
      <%= image_tag @item.image, class:"item-box-img" %>
      <div class="show-format"><%= @item.format.name %></div>
    </div>
    <div class="text-wrapper">
      <div class="show-title"><%= @item.title %></div>
      <div class="show-artist"><%= @item.artist %></div>
      <div class="show-text"><%= @item.text %></div>
      <div class="show-genre"><%= @item.genre.name %></div>
      
      <div class="show-stock">
        <% if @item.stock > 0 %>
          <p class="show-in-stock">在庫あり</p>
        <% else %>
          <p class="show-sold-out">SOLD OUT</p>
        <% end %>
      </div>
      <div class="show-status"><%= @item.status.name %></div>
      <div class="btn-zone">
        <% if @item.stock != 0 && user_signed_in? %>
          <%= link_to item_add_item_path(@item), method: :post do %>
            <button class="to-cart-btn">カートに入れる</button>
          <% end %>
        <% elsif @item.stock == 0 && user_signed_in? %>
        <% else %>
          <%= link_to new_user_session_path do %>
            <button class="to-cart-btn">カートに入れる</button>
          <% end %>
        <% end %>
        <% if user_signed_in? && current_user.admin? %>
          <%= link_to edit_item_path(@item), class:"edit-item-path" do %>
            <button class="to-edit-btn">編集・削除</button>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>